package org.AgileKart.model;

// Generated May 19, 2015 2:48:32 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * AkCategoryOptions generated by hbm2java
 */
@Entity
@Table(name = "ak_category_options"
      , catalog = "agilekart")
@XmlRootElement
public class AkCategoryOptions implements java.io.Serializable
{

   private int categoryOptionId;
   private int categoryId;
   private int optionGroupId;

   public AkCategoryOptions()
   {
   }

   public AkCategoryOptions(int categoryOptionId, int categoryId, int optionGroupId)
   {
      this.categoryOptionId = categoryOptionId;
      this.categoryId = categoryId;
      this.optionGroupId = optionGroupId;
   }

   @Id
   @Column(name = "category_option_id", unique = true, nullable = false)
   public int getCategoryOptionId()
   {
      return this.categoryOptionId;
   }

   public void setCategoryOptionId(int categoryOptionId)
   {
      this.categoryOptionId = categoryOptionId;
   }

   @Column(name = "category_id", nullable = false)
   public int getCategoryId()
   {
      return this.categoryId;
   }

   public void setCategoryId(int categoryId)
   {
      this.categoryId = categoryId;
   }

   @Column(name = "option_group_id", nullable = false)
   public int getOptionGroupId()
   {
      return this.optionGroupId;
   }

   public void setOptionGroupId(int optionGroupId)
   {
      this.optionGroupId = optionGroupId;
   }

}
